version: '3.8'

x-common-migration: &common-migration
  POSTGRES_HOST: ${POSTGRES_HOST:-rpa-mit-reference-data-postgres}
  SCHEMA_ROLE: ${POSTGRES_SCHEMA_ROLE:-postgres}
  SCHEMA_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
  SCHEMA_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-password}
  SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}

x-common-postgres: &common-postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: ${POSTGRES_DB:-rpa_mit_reference_data}
  POSTGRES_USERNAME: ${POSTGRES_ADMIN_USERNAME:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-password}

services:
  database-up:
    image: liquibase/liquibase:3.10.x
    environment:
      << : [*common-migration, *common-postgres]
    entrypoint: >
      sh -c "/scripts/migration/database-up"
    depends_on:
      - rpa-mit-reference-data-postgres
    volumes:
      - ./changelog:/liquibase/changelog
      - ./scripts:/scripts

  database-down:
    image: liquibase/liquibase:3.10.x
    environment:
      << : [*common-migration, *common-postgres]
    entrypoint: >
      sh -c "/scripts/migration/database-down"
    depends_on:
      - rpa-mit-reference-data-postgres
    volumes:
      - ./changelog:/liquibase/changelog
      - ./scripts:/scripts

  rpa-mit-reference-data-postgres:
    image: postgres:15.3-alpine
    environment: *common-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
